spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/rest_api_task
    username: root
    password: P@s4mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    rest:
      base-path: /api/v1

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE